;;; init-persist.el --- Variable state restored early at startup -*- lexical-binding: t; -*-

;;; Commentary:

;; A single place to persist Lisp variable values across sessions.
;;
;; Emacs already has `custom-file' for this, but it is loaded at the very
;; end of `init.el' -- after the modules that need the values have run --
;; and it mixes machine-generated package settings with user state.  Some
;; of this configuration's state, notably the selected theme, must be
;; known *before* those modules run, so this store is loaded early
;; instead (see `init/persist-load', called near the top of `init.el').
;;
;; To persist a new variable:
;;
;;   (require 'init-persist)
;;   (init/persist-register 'my/variable)        ; at module load time
;;   ...
;;   (init/persist-set 'my/variable VALUE)       ; when it changes
;;
;; `init/persist-set' sets the variable and writes the whole store.  When
;; the variable is changed some other way, call
;; `init/persist-save-variable' to write it out.  Registered variables
;; are restored automatically at the next startup.

;;; Code:

(require 'init-lib)

(defconst init/persist-file
  (expand-file-name "persisted-vars.el" user-emacs-directory)
  "File holding all persisted variable values, restored early at startup.")

(defvar init/persist-variables nil
  "List of symbols whose values are written to `init/persist-file'.")

(defun init/persist-register (symbol)
  "Mark SYMBOL for persistence in the store and return it."
  (add-to-list 'init/persist-variables symbol)
  symbol)

(defun init/persist--serialize (symbol)
  "Return a `setq' form, as a string, restoring SYMBOL's current value."
  (format "(setq %s %s)\n"
          symbol
          (prin1-to-string (list 'quote (symbol-value symbol)))))

(defun init/persist-save ()
  "Write every registered, bound variable to `init/persist-file'."
  (init/atomic-write-file
   init/persist-file
   (lambda (temporary)
     (with-temp-file temporary
       (insert ";;; -*- lexical-binding: t; -*-\n"
               ";;; Generated by init-persist.el; do not edit by hand.\n"
               ";;; Persisted variable state, restored early at startup.\n")
       (dolist (symbol (reverse init/persist-variables))
         (when (boundp symbol)
           (insert (init/persist--serialize symbol))))))))

(defun init/persist-save-variable (symbol)
  "Register SYMBOL if needed, then write the whole store."
  (init/persist-register symbol)
  (init/persist-save))

(defun init/persist-set (symbol value)
  "Set SYMBOL to VALUE, then register and persist it."
  (set symbol value)
  (init/persist-save-variable symbol))

(defun init/persist-load ()
  "Restore the persisted variable values.
Call this early in startup, before any module reads a persisted value."
  (when (file-readable-p init/persist-file)
    (load init/persist-file nil 'nomessage)))

(provide 'init-persist)
;;; init-persist.el ends here
