;;; some-nice-colors-theme.el --- Dusty maroon and grass on near-black brown -*- lexical-binding: t; -*-

;;; Commentary:

;; A warm, low-glare dark theme.
;;
;; The surfaces are very dark browns that read as black until something
;; warm sits next to them, so the frame recedes and the code does the
;; talking.  Panels -- mode line, popups, code blocks, the current line --
;; are lifted a few points out of that near-black rather than outlined,
;; which keeps the frame quiet at night.
;;
;; The accents are a dusty maroon rose for anything you define (functions,
;; headings, the selection), a dusty grass green for the words the language
;; owns (keywords), and peach, amber, blue, teal and violet for the rest.
;; Every accent is desaturated enough to look at for a full day.
;;
;; Comments are deliberately not whispered: they sit noticeably brighter
;; than the old warm grey and are panelled with their own slightly lifted
;; background, so a comment reads as a small note pinned to the code.
;;
;; The palette below is the whole theme; every colour used anywhere in the
;; face list is named here, and nothing else is hard-coded.  That is what
;; makes `init/some-nice-colors-edit' able to recolour the whole theme live.

;;; Code:

(deftheme some-nice-colors
  "Dusty maroon, grass green and peach on near-black warm browns.")

(let (;; Surfaces -- near-black warm browns, lifted panel by panel.
      (bg        "#0b0806")  ; canvas
      (bg-dim    "#070504")  ; sunken: inactive mode line, gutters
      (bg-alt    "#160f0c")  ; raised: mode line, popups, tooltips
      (bg-block  "#110c09")  ; code blocks and quoted prose
      (bg-line   "#150e0b")  ; the current line
      (bg-note   "#191211")  ; panelling behind comments and docs
      (bg-glow   "#241a15")  ; hover and transient highlight
      (sel       "#5c2130")  ; the region -- signature maroon
      (sel-dim   "#3a1a22")  ; secondary selection, other search hits
      (border    "#2c201b")  ; boxes, dividers, popup frames
      (border-hi "#4b352b")  ; borders that should be noticed
      ;; Ink
      (fg        "#ded0c4")  ; body text
      (fg-alt    "#b7a698")  ; quieter text, variable uses
      (fg-dim    "#8c7e73")  ; metadata, annotations, punctuation
      (faint     "#55493f")  ; line numbers, rules, furniture
      (comment   "#9e8d80")  ; comments -- lifted, panelled by bg-note
      (doc       "#bda88c")  ; docstrings
      ;; Accents
      (rose      "#c4707f")  ; definitions and headings -- dusty maroon
      (rose-dim  "#9d5c6a")  ; calls, comment ticks, quieter maroon
      (red       "#c85f63")  ; errors
      (grass     "#94c47b")  ; keywords -- dusty grass green
      (green     "#8bbd6f")  ; success and additions
      (peach     "#eeae76")  ; strings
      (amber     "#e0ac62")  ; types and warnings
      (orange    "#d68f5c")  ; numbers and operators
      (blue      "#86b8d4")  ; variables
      (blue-dim  "#6d9ab4")  ; properties and fields
      (teal      "#7cc4ad")  ; constants and escapes
      (violet    "#b294cd")  ; builtins, macros, pragmas
      (cursor    "#eeae76")  ; the point
      ;; Version control
      (add-bg    "#12190e")  ; added lines
      (del-bg    "#221110")  ; removed lines
      (chg-bg    "#1f180d")  ; changed lines
      (add-hi    "#182310")  ; added lines inside the current hunk
      (del-hi    "#2c1614")  ; removed lines inside the current hunk
      (chg-hi    "#2a2110")) ; changed lines inside the current hunk
  (custom-theme-set-faces
   'some-nice-colors

   ;;;; Frame furniture

   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,cursor :foreground ,bg))))
   `(fringe ((t (:background ,bg :foreground ,faint))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(window-divider-first-pixel ((t (:foreground ,bg-alt))))
   `(window-divider-last-pixel ((t (:foreground ,bg-alt))))
   `(internal-border ((t (:background ,bg))))
   `(child-frame-border ((t (:background ,border-hi))))
   `(scroll-bar ((t (:background ,bg-alt :foreground ,border-hi))))
   `(tool-bar ((t (:background ,bg-alt :foreground ,fg-alt))))
   `(tooltip ((t (:background ,bg-alt :foreground ,fg))))
   `(menu ((t (:background ,bg-alt :foreground ,fg))))

   ;;;; Text states

   `(region ((t (:background ,sel :foreground ,fg :extend t))))
   `(secondary-selection ((t (:background ,sel-dim :extend t))))
   `(highlight ((t (:background ,bg-glow :foreground ,fg))))
   `(hl-line ((t (:background ,bg-line :extend t))))
   `(shadow ((t (:foreground ,faint))))
   `(match ((t (:background ,sel-dim :foreground ,peach :weight bold))))
   `(isearch ((t (:background ,peach :foreground ,bg :weight bold))))
   `(isearch-fail ((t (:background ,del-bg :foreground ,red :weight bold))))
   `(lazy-highlight ((t (:background ,sel-dim :foreground ,fg))))
   `(query-replace ((t (:background ,rose :foreground ,bg :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,peach :weight bold))))
   `(escape-glyph ((t (:foreground ,teal))))
   `(homoglyph ((t (:foreground ,amber))))
   `(nobreak-space ((t (:foreground ,faint :underline t))))
   `(nobreak-hyphen ((t (:foreground ,faint))))
   `(trailing-whitespace ((t (:background ,del-hi))))
   `(fill-column-indicator ((t (:foreground ,border :weight thin))))
   `(show-paren-match ((t (:background ,sel :foreground ,peach :weight bold))))
   `(show-paren-match-expression ((t (:background ,bg-block :extend t))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,violet :underline t))))
   `(button ((t (:foreground ,blue :underline t))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,amber :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(help-key-binding ((t (:background ,bg-alt :foreground ,peach
                           :box (:line-width -1 :color ,border)))))
   `(help-argument-name ((t (:foreground ,blue :slant italic))))
   `(whitespace-space ((t (:background ,bg :foreground ,border))))
   `(whitespace-tab ((t (:background ,bg :foreground ,border))))
   `(whitespace-newline ((t (:foreground ,border))))
   `(whitespace-trailing ((t (:background ,del-hi :foreground ,red))))
   `(whitespace-line ((t (:background ,bg-note :foreground ,amber))))
   `(whitespace-indentation ((t (:background ,bg-note :foreground ,faint))))
   `(whitespace-empty ((t (:background ,bg-note))))

   ;;;; Mode line, header line, tab bar

   `(mode-line ((t (:background ,bg-alt :foreground ,fg
                    :box (:line-width -1 :color ,border-hi)))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:background ,bg-dim :foreground ,fg-dim
                             :box (:line-width -1 :color ,border)))))
   `(mode-line-highlight ((t (:background ,bg-glow :foreground ,peach :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,rose :weight bold))))
   `(mode-line-emphasis ((t (:foreground ,peach :weight bold))))
   `(header-line ((t (:background ,bg-alt :foreground ,fg-alt
                      :box (:line-width -1 :color ,border)))))
   `(header-line-highlight ((t (:background ,bg-glow :foreground ,fg))))
   `(line-number ((t (:background ,bg :foreground ,faint))))
   `(line-number-current-line ((t (:background ,bg-line :foreground ,peach :weight bold))))
   `(line-number-major-tick ((t (:background ,bg :foreground ,fg-dim))))
   `(line-number-minor-tick ((t (:background ,bg :foreground ,faint))))
   `(tab-bar ((t (:background ,bg :foreground ,fg-dim :box nil))))
   `(tab-bar-tab ((t (:background ,bg-alt :foreground ,peach :weight bold
                      :box (:line-width (1 . -1) :color ,border-hi)))))
   `(tab-bar-tab-inactive ((t (:background ,bg :foreground ,fg-dim :weight normal
                               :box (:line-width (1 . -1) :color ,border)))))
   `(tab-line ((t (:background ,bg-dim :foreground ,fg-dim))))

   ;;;; doom-modeline

   `(doom-modeline ((t (:inherit mode-line))))
   `(doom-modeline-bar ((t (:background ,rose))))
   `(doom-modeline-bar-inactive ((t (:background ,border))))
   `(doom-modeline-buffer-file ((t (:foreground ,fg :weight semi-bold))))
   `(doom-modeline-buffer-path ((t (:foreground ,fg-dim))))
   `(doom-modeline-buffer-modified ((t (:foreground ,amber :weight bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,grass :weight semi-bold))))
   `(doom-modeline-buffer-minor-mode ((t (:foreground ,fg-dim))))
   `(doom-modeline-project-dir ((t (:foreground ,blue :weight bold))))
   `(doom-modeline-project-root-dir ((t (:foreground ,fg-dim))))
   `(doom-modeline-project-parent-dir ((t (:foreground ,fg-dim))))
   `(doom-modeline-emphasis ((t (:foreground ,peach :weight bold))))
   `(doom-modeline-highlight ((t (:foreground ,peach))))
   `(doom-modeline-panel ((t (:background ,sel :foreground ,fg))))
   `(doom-modeline-info ((t (:foreground ,green))))
   `(doom-modeline-warning ((t (:foreground ,amber))))
   `(doom-modeline-urgent ((t (:foreground ,red))))
   `(doom-modeline-notification ((t (:foreground ,red :weight bold))))
   `(doom-modeline-debug ((t (:foreground ,violet))))
   `(doom-modeline-time ((t (:foreground ,fg-dim))))
   `(doom-modeline-host ((t (:foreground ,teal :slant italic))))
   `(doom-modeline-compilation ((t (:foreground ,amber))))
   `(doom-modeline-lsp-success ((t (:foreground ,green))))
   `(doom-modeline-lsp-warning ((t (:foreground ,amber))))
   `(doom-modeline-lsp-error ((t (:foreground ,red))))
   `(doom-modeline-lsp-running ((t (:foreground ,violet))))
   `(doom-modeline-repl-success ((t (:foreground ,green))))
   `(doom-modeline-repl-warning ((t (:foreground ,amber))))
   `(doom-modeline-vcs-default ((t (:foreground ,teal))))

   ;;;; Syntax

   `(font-lock-builtin-face ((t (:foreground ,violet))))
   `(font-lock-comment-face ((t (:background ,bg-note :foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:background ,bg-note :foreground ,rose-dim
                                           :slant italic))))
   `(font-lock-doc-face ((t (:background ,bg-note :foreground ,doc :slant italic))))
   `(font-lock-doc-markup-face ((t (:background ,bg-note :foreground ,teal))))
   `(font-lock-constant-face ((t (:foreground ,teal))))
   `(font-lock-escape-face ((t (:foreground ,teal :weight bold))))
   `(font-lock-function-name-face ((t (:foreground ,rose :weight semi-bold))))
   `(font-lock-function-call-face ((t (:foreground ,rose-dim))))
   `(font-lock-keyword-face ((t (:foreground ,grass :weight semi-bold))))
   `(font-lock-number-face ((t (:foreground ,orange))))
   `(font-lock-operator-face ((t (:foreground ,orange))))
   `(font-lock-negation-char-face ((t (:foreground ,red :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,violet :slant italic))))
   `(font-lock-property-name-face ((t (:foreground ,blue-dim))))
   `(font-lock-property-use-face ((t (:foreground ,blue-dim))))
   `(font-lock-punctuation-face ((t (:foreground ,fg-dim))))
   `(font-lock-bracket-face ((t (:foreground ,fg-alt))))
   `(font-lock-delimiter-face ((t (:foreground ,fg-dim))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,fg-dim))))
   `(font-lock-regexp-face ((t (:foreground ,amber))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,teal :weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,violet :weight bold))))
   `(font-lock-string-face ((t (:foreground ,peach))))
   `(font-lock-type-face ((t (:foreground ,amber))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(font-lock-variable-use-face ((t (:foreground ,fg-alt))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(highlight-numbers-number ((t (:foreground ,orange))))

   ;;;; Language modes with faces of their own

   `(nim-font-lock-export-face ((t (:foreground ,rose :weight semi-bold))))
   `(nim-font-lock-pragma-face ((t (:foreground ,violet :slant italic))))
   `(nim-font-lock-number-face ((t (:foreground ,orange))))
   `(nim-non-overloadable-face ((t (:foreground ,grass :weight semi-bold))))
   `(owl-function-name-face ((t (:foreground ,rose :weight bold))))
   `(owl-delimiter-face ((t (:foreground ,violet :weight bold))))
   `(owl-selector-face ((t (:foreground ,blue-dim))))
   `(owl-binding-face ((t (:foreground ,blue))))
   `(sh-heredoc ((t (:foreground ,peach))))
   `(sh-quoted-exec ((t (:foreground ,violet))))
   `(css-selector ((t (:foreground ,rose :weight semi-bold))))
   `(css-property ((t (:foreground ,blue-dim))))

   ;;;; Structure and editing aids

   `(parenthesis ((t (:foreground ,faint))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,rose))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,grass))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,blue))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,peach))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,violet))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,teal))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,amber))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,rose-dim))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,blue-dim))))
   `(rainbow-delimiters-base-error-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-mismatched-face ((t (:foreground ,red :weight bold :underline t))))
   `(highlight-indent-guides-character-face ((t (:foreground ,border))))
   `(highlight-indent-guides-stack-character-face ((t (:foreground ,border-hi))))
   `(highlight-indent-guides-top-character-face ((t (:foreground ,rose-dim))))
   `(highlight-indent-guides-odd-face ((t (:background ,bg-block))))
   `(highlight-indent-guides-even-face ((t (:background ,bg))))
   `(yas-field-highlight-face ((t (:background ,sel-dim :foreground ,peach))))
   `(bm-face ((t (:background ,sel-dim :foreground ,peach :extend t))))
   `(bm-persistent-face ((t (:background ,sel :foreground ,fg :extend t))))
   `(bm-fringe-face ((t (:foreground ,peach))))
   `(bm-fringe-persistent-face ((t (:foreground ,rose))))
   `(avy-lead-face ((t (:background ,rose :foreground ,bg :weight bold))))
   `(avy-lead-face-0 ((t (:background ,teal :foreground ,bg :weight bold))))
   `(avy-lead-face-1 ((t (:background ,amber :foreground ,bg :weight bold))))
   `(avy-lead-face-2 ((t (:background ,violet :foreground ,bg :weight bold))))
   `(avy-background-face ((t (:foreground ,faint))))
   `(aw-leading-char-face ((t (:foreground ,rose :height 2.0 :weight bold))))
   `(aw-background-face ((t (:foreground ,faint))))
   `(aw-mode-line-face ((t (:foreground ,peach :weight bold))))

   ;;;; Completion and the minibuffer

   `(completions-common-part ((t (:foreground ,peach :weight bold))))
   `(completions-first-difference ((t (:foreground ,rose))))
   `(completions-annotations ((t (:foreground ,fg-dim :slant italic))))
   `(completions-group-title ((t (:foreground ,rose :slant italic))))
   `(completions-group-separator ((t (:foreground ,border :strike-through t))))
   `(vertico-current ((t (:background ,sel :foreground ,fg :weight semi-bold :extend t))))
   `(vertico-group-title ((t (:foreground ,rose :slant italic))))
   `(vertico-group-separator ((t (:foreground ,border :strike-through t))))
   `(vertico-multiline ((t (:foreground ,fg-dim))))
   `(vertico-mouse ((t (:background ,bg-glow))))
   `(vertico-quick1 ((t (:background ,rose :foreground ,bg :weight bold))))
   `(vertico-quick2 ((t (:background ,teal :foreground ,bg :weight bold))))
   `(orderless-match-face-0 ((t (:foreground ,peach :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,grass :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,blue :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,violet :weight bold))))
   `(corfu-default ((t (:background ,bg-alt :foreground ,fg))))
   `(corfu-current ((t (:background ,sel :foreground ,fg :weight semi-bold))))
   `(corfu-bar ((t (:background ,rose-dim))))
   `(corfu-border ((t (:background ,border-hi))))
   `(corfu-annotations ((t (:foreground ,fg-dim :slant italic))))
   `(corfu-deprecated ((t (:foreground ,fg-dim :strike-through t))))
   `(corfu-echo ((t (:foreground ,fg-dim))))
   `(corfu-indexed ((t (:foreground ,amber))))
   `(corfu-popupinfo ((t (:background ,bg-block :foreground ,fg-alt))))
   `(corfu-quick1 ((t (:background ,rose :foreground ,bg :weight bold))))
   `(corfu-quick2 ((t (:background ,teal :foreground ,bg :weight bold))))
   `(company-tooltip ((t (:background ,bg-alt :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,sel :foreground ,fg :weight semi-bold))))
   `(company-tooltip-common ((t (:foreground ,peach :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,fg-dim :slant italic))))
   `(company-scrollbar-bg ((t (:background ,bg-block))))
   `(company-scrollbar-fg ((t (:background ,rose-dim))))
   `(company-preview ((t (:background ,bg-block :foreground ,fg-dim))))
   `(company-preview-common ((t (:foreground ,teal :background ,bg-block))))
   `(marginalia-key ((t (:foreground ,peach))))
   `(marginalia-documentation ((t (:foreground ,fg-dim :slant italic))))
   `(marginalia-file-name ((t (:foreground ,fg-alt))))
   `(marginalia-file-priv-dir ((t (:foreground ,blue))))
   `(marginalia-file-priv-read ((t (:foreground ,green))))
   `(marginalia-file-priv-write ((t (:foreground ,amber))))
   `(marginalia-file-priv-exec ((t (:foreground ,red))))
   `(marginalia-file-priv-link ((t (:foreground ,teal))))
   `(marginalia-file-priv-no ((t (:foreground ,faint))))
   `(marginalia-size ((t (:foreground ,orange))))
   `(marginalia-date ((t (:foreground ,violet))))
   `(marginalia-number ((t (:foreground ,orange))))
   `(marginalia-char ((t (:foreground ,teal))))
   `(marginalia-string ((t (:foreground ,peach))))
   `(marginalia-symbol ((t (:foreground ,teal))))
   `(marginalia-type ((t (:foreground ,amber))))
   `(marginalia-value ((t (:foreground ,fg))))
   `(marginalia-function ((t (:foreground ,rose))))
   `(marginalia-mode ((t (:foreground ,grass))))
   `(marginalia-modified ((t (:foreground ,red))))
   `(marginalia-lighter ((t (:foreground ,fg-dim))))
   `(marginalia-true ((t (:foreground ,green))))
   `(marginalia-null ((t (:foreground ,faint))))
   `(marginalia-version ((t (:foreground ,violet))))
   `(consult-file ((t (:foreground ,fg-alt))))
   `(consult-key ((t (:foreground ,peach))))
   `(consult-line-number ((t (:foreground ,faint))))
   `(consult-line-number-prefix ((t (:foreground ,faint))))
   `(consult-line-number-wrapped ((t (:foreground ,amber))))
   `(consult-highlight-match ((t (:background ,sel-dim :foreground ,peach :weight bold))))
   `(consult-preview-match ((t (:background ,sel :foreground ,fg :weight bold))))
   `(consult-preview-line ((t (:background ,bg-line :extend t))))
   `(consult-preview-insertion ((t (:background ,bg-block))))
   `(consult-separator ((t (:foreground ,border))))
   `(consult-async-split ((t (:foreground ,rose :weight bold))))
   `(consult-async-running ((t (:foreground ,amber))))
   `(consult-async-finished ((t (:foreground ,green))))
   `(consult-async-failed ((t (:foreground ,red))))
   `(consult-bookmark ((t (:foreground ,violet))))
   `(consult-buffer ((t (:foreground ,fg))))
   `(consult-grep-context ((t (:foreground ,fg-dim))))
   `(consult-imenu-prefix ((t (:foreground ,fg-dim :slant italic))))
   `(consult-narrow-indicator ((t (:foreground ,rose :weight bold))))
   `(embark-keybinding ((t (:foreground ,peach))))
   `(embark-target ((t (:background ,sel-dim :foreground ,peach :weight bold))))
   `(embark-selected ((t (:background ,sel :foreground ,fg))))
   `(embark-collect-group-title ((t (:foreground ,rose :slant italic))))
   `(embark-collect-annotation ((t (:foreground ,fg-dim :slant italic))))
   `(embark-verbose-indicator-title ((t (:foreground ,rose :weight bold :height 1.1))))
   `(embark-verbose-indicator-documentation ((t (:foreground ,fg-dim :slant italic))))
   `(which-key-key-face ((t (:foreground ,peach :weight bold))))
   `(which-key-separator-face ((t (:foreground ,faint))))
   `(which-key-note-face ((t (:foreground ,fg-dim))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-group-description-face ((t (:foreground ,violet :slant italic))))
   `(which-key-local-map-description-face ((t (:foreground ,teal))))
   `(which-key-highlighted-command-face ((t (:foreground ,rose :underline t))))

   ;;;; Diagnostics, compilation and the language server

   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,amber)))))
   `(flycheck-info ((t (:underline (:style wave :color ,teal)))))
   `(flycheck-fringe-error ((t (:foreground ,red :weight bold))))
   `(flycheck-fringe-warning ((t (:foreground ,amber :weight bold))))
   `(flycheck-fringe-info ((t (:foreground ,teal :weight bold))))
   `(flycheck-error-list-error ((t (:foreground ,red))))
   `(flycheck-error-list-warning ((t (:foreground ,amber))))
   `(flycheck-error-list-info ((t (:foreground ,teal))))
   `(flycheck-error-list-line-number ((t (:foreground ,faint))))
   `(flycheck-error-list-column-number ((t (:foreground ,faint))))
   `(flycheck-error-list-filename ((t (:foreground ,blue))))
   `(flycheck-error-list-id ((t (:foreground ,violet))))
   `(flycheck-error-list-checker-name ((t (:foreground ,fg-dim))))
   `(flycheck-error-list-highlight ((t (:background ,bg-line :extend t))))
   `(flycheck-posframe-face ((t (:background ,bg-alt :foreground ,fg))))
   `(flycheck-posframe-background-face ((t (:background ,bg-alt))))
   `(flycheck-posframe-border-face ((t (:foreground ,border-hi))))
   `(flycheck-posframe-error-face ((t (:background ,bg-alt :foreground ,red :weight bold))))
   `(flycheck-posframe-warning-face ((t (:background ,bg-alt :foreground ,amber))))
   `(flycheck-posframe-info-face ((t (:background ,bg-alt :foreground ,teal))))
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,amber)))))
   `(flymake-note ((t (:underline (:style wave :color ,teal)))))
   `(compilation-error ((t (:foreground ,red :weight bold))))
   `(compilation-warning ((t (:foreground ,amber))))
   `(compilation-info ((t (:foreground ,green))))
   `(compilation-line-number ((t (:foreground ,faint))))
   `(compilation-column-number ((t (:foreground ,faint))))
   `(compilation-mode-line-exit ((t (:foreground ,green :weight bold))))
   `(compilation-mode-line-fail ((t (:foreground ,red :weight bold))))
   `(compilation-mode-line-run ((t (:foreground ,amber :weight bold))))
   `(eglot-highlight-symbol-face ((t (:background ,bg-glow :weight bold))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:foreground ,fg-dim :slant italic))))
   `(eglot-diagnostic-tag-deprecated-face ((t (:strike-through t))))
   `(eglot-inlay-hint-face ((t (:height 0.85 :background ,bg-block :foreground ,faint))))
   `(eglot-parameter-hint-face ((t (:inherit eglot-inlay-hint-face :foreground ,blue-dim))))
   `(eglot-type-hint-face ((t (:inherit eglot-inlay-hint-face :foreground ,amber))))
   `(eldoc-highlight-function-argument ((t (:foreground ,peach :weight bold))))
   `(eldoc-box-body ((t (:background ,bg-alt :foreground ,fg))))
   `(eldoc-box-border ((t (:background ,border-hi))))
   `(eldoc-box-markdown-separator ((t (:foreground ,border))))

   ;;;; Version control

   `(diff-added ((t (:background ,add-bg :foreground ,green :extend t))))
   `(diff-removed ((t (:background ,del-bg :foreground ,red :extend t))))
   `(diff-changed ((t (:background ,chg-bg :foreground ,amber :extend t))))
   `(diff-changed-unspecified ((t (:background ,chg-bg :foreground ,amber :extend t))))
   `(diff-refine-added ((t (:background ,add-hi :foreground ,green :weight bold))))
   `(diff-refine-removed ((t (:background ,del-hi :foreground ,red :weight bold))))
   `(diff-refine-changed ((t (:background ,chg-hi :foreground ,amber :weight bold))))
   `(diff-indicator-added ((t (:foreground ,green :weight bold))))
   `(diff-indicator-removed ((t (:foreground ,red :weight bold))))
   `(diff-indicator-changed ((t (:foreground ,amber :weight bold))))
   `(diff-context ((t (:foreground ,fg-dim))))
   `(diff-header ((t (:background ,bg-alt :foreground ,fg-alt :extend t))))
   `(diff-file-header ((t (:background ,bg-alt :foreground ,rose :weight bold :extend t))))
   `(diff-hunk-header ((t (:background ,bg-block :foreground ,violet :extend t))))
   `(diff-function ((t (:foreground ,fg-dim :slant italic))))
   `(diff-nonexistent ((t (:foreground ,faint :strike-through t))))
   `(diff-hl-insert ((t (:background ,green :foreground ,green))))
   `(diff-hl-delete ((t (:background ,red :foreground ,red))))
   `(diff-hl-change ((t (:background ,amber :foreground ,amber))))
   `(diff-hl-reverted-hunk-highlight ((t (:background ,sel :foreground ,fg))))
   `(diff-hl-dired-insert ((t (:foreground ,green))))
   `(diff-hl-dired-delete ((t (:foreground ,red))))
   `(diff-hl-dired-change ((t (:foreground ,amber))))
   `(diff-hl-dired-unknown ((t (:foreground ,fg-dim))))
   `(diff-hl-dired-ignored ((t (:foreground ,faint))))
   `(smerge-upper ((t (:background ,del-bg :extend t))))
   `(smerge-lower ((t (:background ,add-bg :extend t))))
   `(smerge-base ((t (:background ,chg-bg :extend t))))
   `(smerge-markers ((t (:background ,bg-alt :foreground ,violet :weight bold :extend t))))
   `(smerge-refined-added ((t (:background ,add-hi :foreground ,green))))
   `(smerge-refined-removed ((t (:background ,del-hi :foreground ,red))))

   ;;;; Magit

   `(magit-section-heading ((t (:foreground ,rose :weight bold))))
   `(magit-section-secondary-heading ((t (:foreground ,peach :weight bold))))
   `(magit-section-heading-selection ((t (:foreground ,peach))))
   `(magit-section-highlight ((t (:background ,bg-line :extend t))))
   `(magit-section-child-count ((t (:foreground ,fg-dim))))
   `(magit-header-line ((t (:background ,bg-alt :foreground ,rose :weight bold
                            :box (:line-width -1 :color ,border)))))
   `(magit-header-line-key ((t (:foreground ,peach))))
   `(magit-header-line-log-select ((t (:background ,bg-alt :foreground ,fg))))
   `(magit-diff-file-heading ((t (:foreground ,fg :weight semi-bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-glow :weight semi-bold :extend t))))
   `(magit-diff-file-heading-selection ((t (:background ,sel :foreground ,peach :extend t))))
   `(magit-diff-hunk-heading ((t (:background ,bg-block :foreground ,fg-dim :extend t))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg-alt :foreground ,violet :extend t))))
   `(magit-diff-hunk-heading-selection ((t (:background ,sel :foreground ,peach :extend t))))
   `(magit-diff-hunk-region ((t (:background ,sel-dim :extend t))))
   `(magit-diff-lines-heading ((t (:background ,rose :foreground ,bg :extend t))))
   `(magit-diff-lines-boundary ((t (:background ,rose))))
   `(magit-diff-added ((t (:background ,add-bg :foreground ,green :extend t))))
   `(magit-diff-added-highlight ((t (:background ,add-hi :foreground ,green :extend t))))
   `(magit-diff-removed ((t (:background ,del-bg :foreground ,red :extend t))))
   `(magit-diff-removed-highlight ((t (:background ,del-hi :foreground ,red :extend t))))
   `(magit-diff-base ((t (:background ,chg-bg :foreground ,amber :extend t))))
   `(magit-diff-base-highlight ((t (:background ,chg-hi :foreground ,amber :extend t))))
   `(magit-diff-context ((t (:foreground ,fg-dim :extend t))))
   `(magit-diff-context-highlight ((t (:background ,bg-line :foreground ,fg-alt :extend t))))
   `(magit-diff-revision-summary ((t (:foreground ,peach :weight bold))))
   `(magit-diff-revision-summary-highlight ((t (:background ,bg-glow :foreground ,peach :weight bold))))
   `(magit-diff-whitespace-warning ((t (:background ,del-hi))))
   `(magit-diffstat-added ((t (:foreground ,green))))
   `(magit-diffstat-removed ((t (:foreground ,red))))
   `(magit-hash ((t (:foreground ,amber))))
   `(magit-filename ((t (:foreground ,fg-alt))))
   `(magit-dimmed ((t (:foreground ,faint))))
   `(magit-branch-local ((t (:foreground ,blue :weight semi-bold))))
   `(magit-branch-remote ((t (:foreground ,grass :weight semi-bold))))
   `(magit-branch-remote-head ((t (:foreground ,grass :weight bold :box (:line-width -1 :color ,border)))))
   `(magit-branch-current ((t (:foreground ,rose :weight bold :box (:line-width -1 :color ,border-hi)))))
   `(magit-branch-upstream ((t (:foreground ,teal :slant italic))))
   `(magit-branch-warning ((t (:foreground ,amber :weight bold))))
   `(magit-tag ((t (:foreground ,violet :weight semi-bold))))
   `(magit-refname ((t (:foreground ,fg-dim))))
   `(magit-refname-stash ((t (:foreground ,teal))))
   `(magit-refname-wip ((t (:foreground ,amber))))
   `(magit-refname-pullreq ((t (:foreground ,violet))))
   `(magit-keyword ((t (:foreground ,teal))))
   `(magit-keyword-squash ((t (:foreground ,amber :weight bold))))
   `(magit-log-author ((t (:foreground ,rose-dim))))
   `(magit-log-date ((t (:foreground ,faint))))
   `(magit-log-graph ((t (:foreground ,fg-dim))))
   `(magit-process-ok ((t (:foreground ,green :weight bold))))
   `(magit-process-ng ((t (:foreground ,red :weight bold))))
   `(magit-bisect-good ((t (:foreground ,green))))
   `(magit-bisect-bad ((t (:foreground ,red))))
   `(magit-bisect-skip ((t (:foreground ,amber))))
   `(magit-blame-heading ((t (:background ,bg-alt :foreground ,fg-alt :extend t))))
   `(magit-blame-highlight ((t (:background ,bg-glow :foreground ,fg :extend t))))
   `(magit-blame-dimmed ((t (:background ,bg-alt :foreground ,faint :extend t))))
   `(magit-blame-margin ((t (:background ,bg-alt :foreground ,fg-alt))))
   `(magit-blame-name ((t (:foreground ,rose-dim))))
   `(magit-blame-date ((t (:foreground ,faint))))
   `(magit-blame-hash ((t (:foreground ,amber))))
   `(magit-blame-summary ((t (:foreground ,fg-alt))))
   `(magit-sequence-done ((t (:foreground ,green))))
   `(magit-sequence-drop ((t (:foreground ,red))))
   `(magit-sequence-head ((t (:foreground ,blue))))
   `(magit-sequence-onto ((t (:foreground ,fg-dim))))
   `(magit-sequence-part ((t (:foreground ,amber))))
   `(magit-sequence-pick ((t (:foreground ,fg))))
   `(magit-sequence-stop ((t (:foreground ,teal))))
   `(magit-sequence-exec ((t (:foreground ,violet))))
   `(magit-cherry-equivalent ((t (:foreground ,violet))))
   `(magit-cherry-unmatched ((t (:foreground ,teal))))

   ;;;; Files, projects and shells

   `(dired-header ((t (:foreground ,rose :weight bold))))
   `(dired-directory ((t (:foreground ,blue :weight semi-bold))))
   `(dired-symlink ((t (:foreground ,teal :slant italic))))
   `(dired-broken-symlink ((t (:foreground ,red :strike-through t))))
   `(dired-marked ((t (:foreground ,peach :weight bold))))
   `(dired-flagged ((t (:foreground ,red :weight bold))))
   `(dired-perm-write ((t (:foreground ,amber))))
   `(dired-ignored ((t (:foreground ,faint))))
   `(dired-special ((t (:foreground ,violet))))
   `(treemacs-root-face ((t (:foreground ,rose :weight bold :height 1.1))))
   `(treemacs-root-unreadable-face ((t (:foreground ,red :weight bold :height 1.1))))
   `(treemacs-root-remote-face ((t (:foreground ,violet :weight bold :height 1.1))))
   `(treemacs-directory-face ((t (:foreground ,fg-alt))))
   `(treemacs-directory-collapsed-face ((t (:foreground ,fg-dim))))
   `(treemacs-file-face ((t (:foreground ,fg))))
   `(treemacs-tags-face ((t (:foreground ,violet))))
   `(treemacs-term-node-face ((t (:foreground ,teal))))
   `(treemacs-marked-file-face ((t (:background ,sel :foreground ,peach))))
   `(treemacs-hl-line-face ((t (:background ,bg-line :extend t))))
   `(treemacs-fringe-indicator-face ((t (:foreground ,rose))))
   `(treemacs-window-background-face ((t (:background ,bg-dim))))
   `(treemacs-header-button-face ((t (:foreground ,peach :weight bold))))
   `(treemacs-help-title-face ((t (:foreground ,rose :weight bold))))
   `(treemacs-help-column-face ((t (:foreground ,blue))))
   `(treemacs-git-unmodified-face ((t (:foreground ,fg))))
   `(treemacs-git-modified-face ((t (:foreground ,amber))))
   `(treemacs-git-added-face ((t (:foreground ,green))))
   `(treemacs-git-renamed-face ((t (:foreground ,violet :slant italic))))
   `(treemacs-git-conflict-face ((t (:foreground ,red :weight bold))))
   `(treemacs-git-untracked-face ((t (:foreground ,teal))))
   `(treemacs-git-ignored-face ((t (:foreground ,faint))))
   `(treemacs-git-commit-diff-face ((t (:foreground ,rose-dim))))
   `(treemacs-async-loading-face ((t (:foreground ,fg-dim :slant italic))))
   `(eshell-prompt ((t (:foreground ,rose :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,blue :weight semi-bold))))
   `(eshell-ls-executable ((t (:foreground ,green))))
   `(eshell-ls-symlink ((t (:foreground ,teal :slant italic))))
   `(eshell-ls-archive ((t (:foreground ,violet))))
   `(eshell-ls-backup ((t (:foreground ,faint))))
   `(eshell-ls-missing ((t (:foreground ,red))))
   `(eshell-ls-special ((t (:foreground ,amber))))
   `(eshell-ls-unreadable ((t (:foreground ,faint))))
   `(eshell-ls-product ((t (:foreground ,fg-alt))))
   `(eshell-ls-readonly ((t (:foreground ,fg-dim))))

   ;;;; Widgets and Customize -- the palette editor lives here

   `(widget-field ((t (:background ,bg-alt :foreground ,fg
                       :box (:line-width -1 :color ,border)))))
   `(widget-single-line-field ((t (:background ,bg-alt :foreground ,fg
                                   :box (:line-width -1 :color ,border)))))
   `(widget-button ((t (:foreground ,peach :weight bold))))
   `(widget-button-pressed ((t (:foreground ,rose :weight bold))))
   `(widget-documentation ((t (:foreground ,fg-dim :slant italic))))
   `(widget-inactive ((t (:foreground ,faint))))
   `(custom-button ((t (:background ,bg-alt :foreground ,fg
                        :box (:line-width 1 :color ,border-hi)))))
   `(custom-button-mouse ((t (:background ,bg-glow :foreground ,fg
                              :box (:line-width 1 :color ,border-hi)))))
   `(custom-button-pressed ((t (:background ,sel :foreground ,fg
                                :box (:line-width 1 :color ,border-hi)))))
   `(custom-group-tag ((t (:foreground ,rose :weight bold :height 1.2))))
   `(custom-group-subtitle ((t (:foreground ,peach :weight bold))))
   `(custom-variable-tag ((t (:foreground ,blue :weight bold))))
   `(custom-variable-obsolete ((t (:foreground ,faint :strike-through t))))
   `(custom-face-tag ((t (:foreground ,violet :weight bold))))
   `(custom-state ((t (:foreground ,green))))
   `(custom-changed ((t (:foreground ,amber))))
   `(custom-modified ((t (:foreground ,amber))))
   `(custom-set ((t (:foreground ,green))))
   `(custom-invalid ((t (:foreground ,red :weight bold))))
   `(custom-rogue ((t (:foreground ,red))))
   `(custom-comment ((t (:background ,bg-note :foreground ,comment))))
   `(custom-comment-tag ((t (:foreground ,fg-dim))))
   `(custom-link ((t (:foreground ,blue :underline t))))

   ;;;; This configuration's own faces

   `(pulldown-menu-default ((t (:background ,bg-alt :foreground ,fg))))
   `(pulldown-menu-selection ((t (:background ,sel :foreground ,fg :weight semi-bold :extend t))))
   `(pulldown-menu-key ((t (:foreground ,fg-dim))))
   `(pulldown-menu-arrow ((t (:foreground ,rose-dim))))
   `(pulldown-menu-separator ((t (:foreground ,border))))
   `(pulldown-menu-disabled ((t (:foreground ,faint))))
   `(pulldown-menu-border ((t (:foreground ,border-hi))))
   `(init/toolbar-button ((t (:foreground ,peach :weight bold))))
   `(init/toolbar-info ((t (:foreground ,fg-dim))))
   `(init/project-panel-name ((t (:foreground ,rose :weight bold))))
   `(init/project-panel-url ((t (:foreground ,faint))))
   `(init/project-panel-clean ((t (:foreground ,green))))
   `(init/project-panel-dirty ((t (:foreground ,amber))))
   `(init/project-panel-busy ((t (:foreground ,violet :slant italic))))
   `(init/project-panel-button ((t (:foreground ,blue :weight bold :underline nil))))
   `(init/org-table-header ((t (:background ,bg-alt :foreground ,peach :weight bold
                                :overline ,border-hi :extend t))))
   `(init/org-table-stripe ((t (:background ,bg-block :extend t))))
   `(init/org-tag ((t (:background ,sel-dim :foreground ,rose))))

   ;;;; Org

   `(org-document-title ((t (:height 220 :foreground ,rose :weight bold))))
   `(org-document-info ((t (:height 150 :foreground ,blue))))
   `(org-document-info-keyword ((t (:height 80 :foreground ,faint))))
   `(org-level-1 ((t (:height 200 :foreground ,rose :weight bold))))
   `(org-level-2 ((t (:height 150 :foreground ,peach :weight bold))))
   `(org-level-3 ((t (:height 130 :foreground ,blue))))
   `(org-level-4 ((t (:height 120 :foreground ,grass))))
   `(org-level-5 ((t (:height 120 :foreground ,teal))))
   `(org-level-6 ((t (:height 120 :foreground ,violet))))
   `(org-level-7 ((t (:height 120 :foreground ,amber))))
   `(org-level-8 ((t (:height 120 :foreground ,fg-alt))))
   `(org-headline-done ((t (:foreground ,faint))))
   `(org-block ((t (:background ,bg-block :extend t))))
   `(org-block-begin-line ((t (:height 80 :background ,bg-block :foreground ,faint :extend t))))
   `(org-block-end-line ((t (:height 80 :background ,bg-block :foreground ,faint :extend t))))
   `(org-code ((t (:foreground ,teal))))
   `(org-verbatim ((t (:foreground ,peach))))
   `(org-quote ((t (:background ,bg-block :foreground ,doc :slant italic :extend t))))
   `(org-verse ((t (:background ,bg-block :slant italic :extend t))))
   `(org-table ((t (:foreground ,blue-dim))))
   `(org-table-header ((t (:background ,bg-alt :foreground ,peach :weight bold))))
   `(org-drawer ((t (:foreground ,faint))))
   `(org-special-keyword ((t (:foreground ,faint))))
   `(org-property-value ((t (:foreground ,fg-dim))))
   `(org-meta-line ((t (:foreground ,faint :slant italic))))
   `(org-link ((t (:foreground ,blue :underline t))))
   `(org-footnote ((t (:foreground ,teal :underline t))))
   `(org-date ((t (:foreground ,violet :underline t))))
   `(org-todo ((t (:foreground ,rose :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))
   `(org-tag ((t (:foreground ,rose-dim :weight normal))))
   `(org-ellipsis ((t (:foreground ,faint :underline nil))))
   `(org-checkbox ((t (:foreground ,amber :weight bold))))
   `(org-checkbox-statistics-todo ((t (:foreground ,amber :weight bold))))
   `(org-checkbox-statistics-done ((t (:foreground ,green :weight bold))))
   `(org-list-dt ((t (:foreground ,peach :weight bold))))
   `(org-priority ((t (:foreground ,violet :weight bold))))
   `(org-warning ((t (:foreground ,red :weight bold))))
   `(org-agenda-structure ((t (:foreground ,rose :weight bold :height 1.1))))
   `(org-agenda-date ((t (:foreground ,blue))))
   `(org-agenda-date-today ((t (:foreground ,peach :weight bold :slant italic))))
   `(org-agenda-date-weekend ((t (:foreground ,blue-dim))))
   `(org-agenda-done ((t (:foreground ,green))))
   `(org-agenda-clocking ((t (:background ,sel-dim :extend t))))
   `(org-scheduled ((t (:foreground ,grass))))
   `(org-scheduled-today ((t (:foreground ,green :weight semi-bold))))
   `(org-scheduled-previously ((t (:foreground ,amber))))
   `(org-upcoming-deadline ((t (:foreground ,rose))))
   `(org-imminent-deadline ((t (:foreground ,red :weight bold))))
   `(org-time-grid ((t (:foreground ,faint))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-modern-symbol ((t (:foreground ,rose-dim))))
   `(org-modern-label ((t (:background ,sel-dim :foreground ,fg-alt))))
   `(org-modern-tag ((t (:background ,sel-dim :foreground ,rose))))
   `(org-modern-todo ((t (:background ,sel :foreground ,peach :weight bold))))
   `(org-modern-done ((t (:background ,bg-block :foreground ,green :weight bold))))
   `(org-modern-date-active ((t (:background ,bg-alt :foreground ,violet))))
   `(org-modern-date-inactive ((t (:background ,bg-block :foreground ,faint))))
   `(org-modern-time-active ((t (:background ,violet :foreground ,bg))))
   `(org-modern-time-inactive ((t (:background ,bg-alt :foreground ,faint))))
   `(org-modern-statistics ((t (:foreground ,fg-dim))))
   `(org-modern-priority ((t (:background ,bg-alt :foreground ,violet :weight bold))))
   `(org-modern-horizontal-rule ((t (:foreground ,border :strike-through ,border))))
   `(org-modern-block-name ((t (:foreground ,faint :height 0.9))))
   `(org-modern-progress-complete ((t (:background ,grass :foreground ,bg))))
   `(org-modern-progress-incomplete ((t (:background ,bg-alt :foreground ,fg-dim))))
   `(org-modern-internal-target ((t (:foreground ,teal))))
   `(org-modern-radio-target ((t (:foreground ,teal))))

   ;;;; Markdown and prose

   `(markdown-header-delimiter-face ((t (:foreground ,faint))))
   `(markdown-header-rule-face ((t (:foreground ,border))))
   `(markdown-markup-face ((t (:foreground ,faint))))
   `(markdown-inline-code-face ((t (:foreground ,teal))))
   `(markdown-list-face ((t (:foreground ,rose-dim))))
   `(markdown-blockquote-face ((t (:background ,bg-block :foreground ,doc :slant italic))))
   `(markdown-code-face ((t (:background ,bg-block :extend t))))
   `(markdown-pre-face ((t (:background ,bg-block :foreground ,peach :extend t))))
   `(markdown-language-keyword-face ((t (:foreground ,faint :slant italic))))
   `(markdown-url-face ((t (:foreground ,faint))))
   `(markdown-link-face ((t (:foreground ,blue :weight semi-bold))))
   `(markdown-highlight-face ((t (:background ,sel-dim :foreground ,peach))))
   `(markdown-gfm-checkbox-face ((t (:foreground ,amber))))
   `(shr-h1 ((t (:foreground ,rose :weight bold :height 1.4))))
   `(shr-h2 ((t (:foreground ,peach :weight bold :height 1.2))))
   `(shr-h3 ((t (:foreground ,blue :weight bold :height 1.1))))
   `(shr-h4 ((t (:foreground ,grass :weight bold))))
   `(shr-code ((t (:background ,bg-block :foreground ,teal))))
   `(shr-link ((t (:foreground ,blue :underline t))))
   `(info-title-1 ((t (:foreground ,rose :weight bold :height 1.3))))
   `(info-title-2 ((t (:foreground ,peach :weight bold :height 1.2))))
   `(info-title-3 ((t (:foreground ,blue :weight bold :height 1.1))))
   `(info-title-4 ((t (:foreground ,grass :weight bold))))
   `(info-menu-header ((t (:foreground ,rose :weight bold))))
   `(info-menu-star ((t (:foreground ,peach))))
   `(info-node ((t (:foreground ,peach :weight bold :slant italic))))
   `(info-xref ((t (:foreground ,blue :underline t))))
   `(info-xref-visited ((t (:foreground ,violet :underline t))))

   ;;;; Terminal colours

   `(ansi-color-black ((t (:background ,bg-alt :foreground ,bg-alt))))
   `(ansi-color-red ((t (:background ,red :foreground ,red))))
   `(ansi-color-green ((t (:background ,grass :foreground ,grass))))
   `(ansi-color-yellow ((t (:background ,amber :foreground ,amber))))
   `(ansi-color-blue ((t (:background ,blue :foreground ,blue))))
   `(ansi-color-magenta ((t (:background ,rose :foreground ,rose))))
   `(ansi-color-cyan ((t (:background ,teal :foreground ,teal))))
   `(ansi-color-white ((t (:background ,fg-alt :foreground ,fg-alt))))
   `(ansi-color-bright-black ((t (:background ,faint :foreground ,faint))))
   `(ansi-color-bright-red ((t (:background ,rose :foreground ,rose))))
   `(ansi-color-bright-green ((t (:background ,green :foreground ,green))))
   `(ansi-color-bright-yellow ((t (:background ,peach :foreground ,peach))))
   `(ansi-color-bright-blue ((t (:background ,blue-dim :foreground ,blue-dim))))
   `(ansi-color-bright-magenta ((t (:background ,violet :foreground ,violet))))
   `(ansi-color-bright-cyan ((t (:background ,teal :foreground ,teal))))
   `(ansi-color-bright-white ((t (:background ,fg :foreground ,fg))))
   `(term-color-black ((t (:background ,bg-alt :foreground ,bg-alt))))
   `(term-color-red ((t (:background ,red :foreground ,red))))
   `(term-color-green ((t (:background ,grass :foreground ,grass))))
   `(term-color-yellow ((t (:background ,amber :foreground ,amber))))
   `(term-color-blue ((t (:background ,blue :foreground ,blue))))
   `(term-color-magenta ((t (:background ,rose :foreground ,rose))))
   `(term-color-cyan ((t (:background ,teal :foreground ,teal))))
   `(term-color-white ((t (:background ,fg-alt :foreground ,fg-alt)))))

  (custom-theme-set-variables
   'some-nice-colors
   `(ansi-color-names-vector [,bg-alt ,red ,grass ,amber ,blue ,rose ,teal ,fg-alt])
   `(rainbow-delimiters-max-face-count 9)
   `(pdf-view-midnight-colors (cons ,fg ,bg))))

(provide-theme 'some-nice-colors)
;;; some-nice-colors-theme.el ends here
