;;; some-nice-colors-theme.el --- Black background with deep pastel colors -*- lexical-binding: t; -*-

(deftheme some-nice-colors
  "Colorful theme with a pure black background and deep pastel accents.")

(let ((bg "#000000")
      (bg-alt "#0f0f0f")
      (fg "#ececf1")
      (fg-alt "#bdbdcc")
      (cursor "#ffb86c")
      (red "#ff6f91")
      (orange "#ffb86c")
      (yellow "#d8c38a")
      (green "#8be9a8")
      (teal "#72f1d1")
      (cyan "#7cdfff")
      (blue "#8db7ff")
      (violet "#b39dff")
      (magenta "#d98fa8"))
  (custom-theme-set-faces
   'some-nice-colors
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,cursor))))
   `(fringe ((t (:background ,bg :foreground ,fg-alt))))
   `(region ((t (:background "#20223a"))))
   `(highlight ((t (:background "#171726"))))
   `(shadow ((t (:foreground "#7f7f97"))))
   `(minibuffer-prompt ((t (:foreground ,cyan :weight bold))))
   `(vertical-border ((t (:foreground "#1f1f1f"))))
   `(link ((t (:foreground ,blue :underline t))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(mode-line ((t (:background ,bg-alt :foreground ,fg :box (:line-width -1 :color "#2a2a2a")))))
   `(mode-line-inactive ((t (:background "#0a0a0a" :foreground ,fg-alt :box (:line-width -1 :color "#1a1a1a")))))
   `(font-lock-builtin-face ((t (:foreground ,violet))))
   `(font-lock-comment-face ((t (:foreground "#8f8fa8" :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground "#73738e"))))
   `(font-lock-constant-face ((t (:foreground ,teal))))
   `(font-lock-doc-face ((t (:foreground "#a7a7c8"))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight semi-bold))))
   `(font-lock-keyword-face ((t (:foreground ,magenta :weight semi-bold))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,orange))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(isearch ((t (:background ,yellow :foreground ,bg :weight bold))))
   `(lazy-highlight ((t (:background "#30406f" :foreground ,fg))))
   `(show-paren-match ((t (:background "#25254a" :foreground ,cyan :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))
   `(line-number ((t (:foreground "#5f5f74" :background ,bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,bg-alt))))
   `(header-line ((t (:background ,bg-alt :foreground ,fg-alt :box nil))))
   `(hl-line ((t (:background "#101018"))))
   `(trailing-whitespace ((t (:background "#4a001f"))))
   `(company-tooltip ((t (:background "#101010" :foreground ,fg))))
   `(company-tooltip-selection ((t (:background "#1b1b2a"))))
   `(company-tooltip-common ((t (:foreground ,cyan :weight bold))))
   `(company-scrollbar-bg ((t (:background "#111111"))))
   `(company-scrollbar-fg ((t (:background "#333333"))))
   `(company-preview-common ((t (:foreground ,teal :background ,bg)))))

  (custom-theme-set-variables
   'some-nice-colors
   `(ansi-color-names-vector [,bg ,red ,green ,yellow ,blue ,magenta ,cyan ,fg])))

(provide-theme 'some-nice-colors)
;;; some-nice-colors-theme.el ends here
